services:
  - type: web
    name: video-calling-interview-platform
    runtime: node
    buildCommand: npm install --prefix backend && npm install --prefix frontend && npm run build --prefix frontend
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DB_URL
        scope: all
      - key: CLIENT_URL
        scope: all
      - key: INNGEST_EVENT_KEY
        scope: all
      - key: INNGEST_SIGNING_KEY
        scope: all
      - key: STREAM_API_KEY
        scope: all
      - key: STREAM_API_SECRET
        scope: all
