services:
  - type: web
    name: video-calling-interview-platform
    runtime: node
    buildCommand: npm run render-build
    startCommand: npm run render-start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DB_URL
        scope: all
      - key: CLIENT_URL
        scope: all
      - key: ADMIN_EMAILS
        scope: all
      - key: ADMIN_CLERK_IDS
        scope: all
      - key: JUDGE0_API_URL
        value: https://ce.judge0.com
      - key: JUDGE0_API_KEY
        scope: all
      - key: JUDGE0_API_HOST
        scope: all
      - key: JUDGE0_API_TIMEOUT_MS
        value: 20000
      - key: JUDGE0_POLL_INTERVAL_MS
        value: 1000
      - key: JUDGE0_MAX_POLL_ATTEMPTS
        value: 20
      - key: INNGEST_EVENT_KEY
        scope: all
      - key: INNGEST_SIGNING_KEY
        scope: all
      - key: STREAM_API_KEY
        scope: all
      - key: STREAM_API_SECRET
        scope: all





